### ISSUE TITLE
Error: java: cannot access org.arquillian.rusheye.suite.ComparisonResult

### ISSUE THREAD

**Issue by patilpradnya** [vinsguru/ocular#11]
I am getting : Error: java: cannot access org.arquillian.rusheye.suite.ComparisonResult

on "return result.isEqualsImages();" in the following code.

  private boolean verifyChart(String fileName, WebElement element) {

        Path path = Paths.get(fileName);

        OcularResult result = Ocular.snapshot()
                .from(path)
                .sample()
                .using(driver)
                .element(element)
                .compare();

        return result.isEqualsImages();
  }

I am using Intellij. I have imported the lib by drag drop the ocular-1.0.0.Alpha.jar file into lib folder and then did "Add as library". I have written a sample test and page object by following your README as is. 

Am I missing something ?

**Comment by vinsguru** [comment]
I am not sure what you mean by you dragged and dropped the jar! It is a maven dependency. Are you using maven? Did you add the maven dependency?

**Comment by patilpradnya** [comment]
I am not using Maven. I am using ant.

**Comment by vinsguru** [comment]
I see! Ocular is not a single jar. It depends on few other libraries. So dragging and dropping jar will not work. It is not recommended to use that way. You need to use maven/gradle as the README says. Maven will take care of downloading all the dependencies for you! I would suggest you to use maven. (Not for this Ocular. Maven brings a lot of advantages over Ant)

**Comment by patilpradnya** [comment]
Using Maven is not an option for me at this point as I am working on a legacy project. Can you please list down all the libraries that Ocular is using so I can manually get them ?

**Comment by patilpradnya** [comment]
ok. so from the pom file it seems like ocular depends on selenium , testNG and arquillian-rusheye. I am already using selenium and testNG in my project. I ll only need arquillian-rusheye additionally . is that right ?
