### ISSUE TITLE
Maven missing artifact

### ISSUE THREAD

**Issue by deividbatfish2** [vinsguru/ocular#2]
Hello,

After add your library in my pom.xml, maven report n missing artifacts:

Missing artifact com.beust:jcommander:jar:1.64
Missing artifact com.google.code.findbugs:jsr305:jar:1.3.9
Missing artifact com.google.code.gson:gson:jar:2.8.0
Missing artifact com.google.errorprone:error_prone_annotations:jar:2.0.18
Missing artifact com.google.guava:guava:jar:23.0
Missing artifact com.google.j2objc:j2objc-annotations:jar:1.1
Missing artifact com.sun.msv.datatype.xsd:xsdlib:jar:2009.1
Missing artifact com.testautomationguru.ocular:ocular:jar:1.0.0.Alpha
Missing artifact commons-codec:commons-codec:jar:1.10
Missing artifact commons-io:commons-io:jar:1.4
Missing artifact commons-lang:commons-lang:jar:2.4
Missing artifact commons-logging:commons-logging:jar:1.2
Missing artifact dom4j:dom4j:jar:1.6.1
Missing artifact isorelax:isorelax:jar:20030108
Missing artifact javassist:javassist:jar:3.8.0.GA
Missing artifact javax.xml.stream:stax-api:jar:1.0-2
Missing artifact net.bytebuddy:byte-buddy:jar:1.7.5
Missing artifact net.java.dev.jna:jna-platform:jar:4.1.0
Missing artifact net.java.dev.jna:jna:jar:4.1.0
Missing artifact net.java.dev.msv:msv-core:jar:2009.1
Missing artifact net.java.dev.msv:msv-testharness:jar:2009.1
Missing artifact net.sf:jargs:jar:1.0
Missing artifact org.apache.ant:ant-launcher:jar:1.7.1
Missing artifact org.apache.ant:ant:jar:1.7.1
Missing artifact org.apache.commons:commons-exec:jar:1.3
Missing artifact org.apache.httpcomponents:httpclient:jar:4.5.3
Missing artifact org.apache.httpcomponents:httpcore:jar:4.4.6
Missing artifact org.arquillian.rusheye:rusheye-api:jar:1.0.0
Missing artifact org.arquillian.rusheye:rusheye-impl:jar:1.0.0
Missing artifact org.codehaus.mojo:animal-sniffer-annotations:jar:1.14
Missing artifact org.codehaus.woodstox:stax2-api:jar:3.0.3
Missing artifact org.codehaus.woodstox:woodstox-core-lgpl:jar:4.0.9
Missing artifact org.seleniumhq.selenium:selenium-api:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-chrome-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-edge-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-firefox-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-ie-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-java:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-opera-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-remote-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-safari-driver:jar:3.6.0
Missing artifact org.seleniumhq.selenium:selenium-support:jar:3.6.0
Missing artifact org.testng:testng:jar:6.11
Missing artifact org.yaml:snakeyaml:jar:1.17
Missing artifact relaxngDatatype:relaxngDatatype:jar:20020414
Missing artifact xerces:xercesImpl:jar:2.9.1
Missing artifact xml-apis:xml-apis:jar:1.0.b2
Missing artifact xml-resolver:xml-resolver:jar:1.2
No versions available for org.seleniumhq.selenium:selenium-support:jar:[3.3.1,4.0.0) within specified range

Exist some problem with version of this libraries?

**Comment by vinsguru** [comment]
Are you using eclipse?

**Comment by deividbatfish2** [comment]
Yes, version: Oxygen.1a Release (4.7.1a) actually

**Comment by vinsguru** [comment]
I feel it is something to do with eclipse. What doe it happen in command line? like 'mvn clean test' ?

**Comment by deividbatfish2** [comment]
Success. The libraries are downloading and the build is complete. The problems only occur in eclipse.

**Comment by vinsguru** [comment]
Ok, Thanks.
