### ISSUE TITLE
@Snap( ) - this does not accept a method with return type string

### ISSUE THREAD

**Issue by rahulr892** [vinsguru/ocular#4]
@vinsguru 

@Snap( ) - this does not accept a method with return type string in page object class

My requirement is to run tests on multiple platforms with almost similar UI but different projects hence different URL
It also isn't accepting a constant which fetches value from a method and throws error - Attribute value must be a constant.

Can you help ?

**Comment by vinsguru** [comment]
@rahulr892 

It is nothing do with this Snap annotation. Java annotations do not accept variables in the class level.  But you should be able to try this approach.

Insert a parameter as shown here - replace the value at run time

```
@Snap("RichFace-#{THEME}.png")
public class RichFace {

	private final WebDriver driver;

	public RichFace(WebDriver driver){
		this.driver = driver;
	}

	public OcularResult compare() {
		return Ocular
			.snapshot()
				.from(this)
				.replaceAttribute("THEME","ruby") // lets the ocular look for RichFace-ruby.png
			.sample()
				.using(driver)
			.compare();
	}
}
```

**Comment by rahulr892** [comment]
Your above solution works. 
Thanks for the help. 
And keep up the phenomenal work with your blog. Learned some great things from your blog.
Absolutely love it.
